name:        Guidelines MD
description: A collection of best practices from professional organizations, curated by doctors, for doctors

url:         http://localhost:4000
author:      author-config

show_drafts: false

relative_permalinks: false

permalink:     :title

markdown: kramdown

base_url: /guidelinesmd